// -----------------------------------------------------------------------------
// This file is automatically generated by hdl-registers version 8.1.0.
// Code generator CHeaderGenerator version 1.0.0.
// Generated 2026-03-12 13:16 from file regs_counter.toml at Git commit 47448a42394d (local changes present).
// Register hash 9f2e9f9fb5bf3815563ea5a3035766ab50f3a8bb.
// -----------------------------------------------------------------------------

#ifndef COUNTER_REGS_H
#define COUNTER_REGS_H


// Number of registers within this register list.
#define COUNTER_NUM_REGS (3u)

// Type for this register list.
typedef struct counter_regs_t
{
  // Mode "Read, Write".
  uint32_t conf;
  // Mode "Write-pulse".
  uint32_t command;
  // Mode "Read".
  uint32_t status;
} counter_regs_t;

// Address of the 'conf' register.
// Mode 'Read, Write'.
#define COUNTER_CONF_INDEX (0u)
#define COUNTER_CONF_ADDR (4u * COUNTER_CONF_INDEX)
// Attributes for the 'condition' field in the 'conf' register.
#define COUNTER_CONF_CONDITION_SHIFT (0u)
#define COUNTER_CONF_CONDITION_MASK (0b11u << 0u)
#define COUNTER_CONF_CONDITION_MASK_INVERSE (~COUNTER_CONF_CONDITION_MASK)
enum CounterConfCondition
{
  COUNTER_CONF_CONDITION_CLOCK_CYCLES = 0,
  COUNTER_CONF_CONDITION_CLOCK_CYCLES_WITH_ENABLE = 1,
  COUNTER_CONF_CONDITION_ENABLE_EDGES = 2,
};
// Attributes for the 'increment' field in the 'conf' register.
#define COUNTER_CONF_INCREMENT_SHIFT (2u)
#define COUNTER_CONF_INCREMENT_MASK (0b11111111u << 2u)
#define COUNTER_CONF_INCREMENT_MASK_INVERSE (~COUNTER_CONF_INCREMENT_MASK)

// Address of the 'command' register.
// Mode 'Write-pulse'.
#define COUNTER_COMMAND_INDEX (1u)
#define COUNTER_COMMAND_ADDR (4u * COUNTER_COMMAND_INDEX)
// Attributes for the 'reset_counter' field in the 'command' register.
#define COUNTER_COMMAND_RESET_COUNTER_SHIFT (0u)
#define COUNTER_COMMAND_RESET_COUNTER_MASK (0b1u << 0u)
#define COUNTER_COMMAND_RESET_COUNTER_MASK_INVERSE (~COUNTER_COMMAND_RESET_COUNTER_MASK)

// Address of the 'status' register.
// Mode 'Read'.
#define COUNTER_STATUS_INDEX (2u)
#define COUNTER_STATUS_ADDR (4u * COUNTER_STATUS_INDEX)
// Attributes for the 'enabled' field in the 'status' register.
#define COUNTER_STATUS_ENABLED_SHIFT (0u)
#define COUNTER_STATUS_ENABLED_MASK (0b1u << 0u)
#define COUNTER_STATUS_ENABLED_MASK_INVERSE (~COUNTER_STATUS_ENABLED_MASK)
// Attributes for the 'pulse_count' field in the 'status' register.
#define COUNTER_STATUS_PULSE_COUNT_SHIFT (1u)
#define COUNTER_STATUS_PULSE_COUNT_MASK (0b1111111111111111u << 1u)
#define COUNTER_STATUS_PULSE_COUNT_MASK_INVERSE (~COUNTER_STATUS_PULSE_COUNT_MASK)

#endif // COUNTER_REGS_H
